### ISSUE TITLE
Your soft killed my criket

### ISSUE THREAD

**Issue by porlock** [sobieh/bttrelay#1]
My beloved cricket.. "cricky" was playing with me, i thought the printer is off but your relay fail to do it successfully, poor poor cricky, he touched terminal connector with his antennas, and now he's gone. you bastard !

It's me kissing Cricky for good bye 

![image](https://user-images.githubusercontent.com/18246301/198414083-87bd629e-5a15-49e8-a7ef-c497a51935cf.png)

**Comment by sobieh** [comment]
R.I.P
