### ISSUE TITLE
Change delay time and initial state.

### ISSUE THREAD

**Issue by yzheka** [sobieh/bttrelay#2]
Can you please help me. I want to adapt this relay to use with klipper firmware. For this I need the ON delay be a 60 sec long to allow raspberry pi to boot. Also it would be great to make relay off by default when you plug the power, so ON state can be switched only by signal pin.

**Comment by sobieh** [comment]
There is no delay time in this firmware mod.
It simply turns ON or OFF depending on the signal with 3 seconds resolution.

I can build and upload default OFF version. No problem but 60 sec delay would make it react with 60 sec lag to turn on or off.
It will also invert the input signal so it will be like +5v = ON / GND = OFF and default mode is OFF.

If you need it for Klipper then you can do the trick with **boot/config.txt** like (add on bottom):
```
[all]
#change 16 to your power signal pin
gpio=16=op,dl
```

It will set the pin to LOW (GND) as soon as the board boots and keep your printer ON.

Then in your moonraker.cfg set:
```
[power printer]
type: gpio
pin: !gpio16  # inverted!
restart_klipper_when_powered: True
initial_state: on
locked_while_printing: True
off_when_shutdown: True
on_when_job_queued: True
```

On how to set print auto off etc. you can read in klipper docs.

**Comment by yzheka** [comment]
@sobieh thanks for advice. Is there any way to add initial delay for reading power ON signal? without that I need to hold power button untill pi boots and puts HIGH to power signal pin

**Comment by lyntoo** [comment]
Thanks for your reverse engineering! Did you disassemble the official firmware with something like d52?. I try figure out to use btt relay for another purpose like the same official function with more delay on off time like 45s - 1min. I'm new to the 8051 asm build, I look at your working files and interest me at learning about micro program.

**Comment by sobieh** [comment]
Hi, yes i was using mostly D52 and manual analysis. Unfortunately there is no easy way to do this.
